language: node_js
node_js:
  - "0.10"
env:
  - a="--karma single-run"
  - a="--karma single-run" BROWSERS=Firefox
  - a=""
matrix:
  # just run integration tests on other node versions
  include:
    - node_js: "0.11"
      env: a=""
  allow_failures:
    - node_js: "0.11"
      env: a=""
  
notifications:
  email:
    recipients:
      - commits@onilabs.com
    on_success: change
    on_failure: always

branches:
  # build only master and release braches
  only:
    - master
    - /^\d+(\.\d+)+$/

script: "./conductance test/run.mho $a --show-failed"

