language: node_js
node_js:
  - "0.10"
env:
  - a="--karma single-run"
  - a=""
matrix:
  # just run nodejs tests on other node versions
  include:
    - node_js: "0.11"
      env: a=""
    - node_js: "0.8"
      env: a=""
  allow_failures:
    - node_js: "0.11"
      env: a=""
  
notifications:
  email:
    recipients:
      - commits@onilabs.com
    on_success: change
    on_failure: always

script: "./conductance test/run.mho --show-failed $a"

