language: node_js
node_js:
  - "0.10"
env:
  - a="test/run test/integration/ssh-client-tests.sjs"

install: "npm install --production stratifiedjs ssh2"

branches:
  only:
    - travis-test

script: "node --expose-gc ./conductance exec $a"

