language: node_js
node_js:
  - v4
  - v6
  - v7
env:
  - a="test/run --karma single-run"
  - a="test/run --karma single-run" BROWSERS=Firefox
  - a="test/run"

# workaround https://github.com/npm/npm/issues/6679
install: "npm install --production && ./tools/gup node_modules/update"

notifications:
  email:
    recipients:
      - commits@onilabs.com
    on_success: change
    on_failure: always
  hipchat:
    rooms:
      secure: WuyQPqKVxrDykbFkXVRZcPQNa0dmmTzpb+xEzBqCwOhyCeTQTAon1HIUEQtmwPJmTwBZX7dTGwa5kOnbCN47quVaOMkkJVsXQFzlDVv9aWz8XH5Hoj50odHFcTJvhjLKoL9wwG6B2z3PTDuP9PyifQBnIUwW3ihaXFmNGDj5ri0=
    template:
      - '%{repository_name}#%{commit} (%{author}): %{message} [%{build_url}]'
    on_success: change
    on_failure: always

branches:
  # build only master and release braches
  only:
    - master
    - /^\d+(\.\d+)+$/

script: "node --expose-gc ./conductance exec $a"

